# Generated by Django 2.1.7 on 2019-03-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=50, verbose_name='Страна')),
                ('city', models.TextField(default='', max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.TextField(max_length=50, verbose_name='Название события')),
                ('date', models.DateField(default='01.01.2000', verbose_name='Дата события')),
                ('teams', models.TextField(default='', max_length=50, verbose_name='Команды участники')),
                ('visitors', models.IntegerField(default=0, verbose_name='Количество зрителей')),
                ('score', models.CharField(max_length=5, verbose_name='Счёт')),
                ('photo', models.TextField(default='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.TextField(default='', max_length=50, verbose_name='Название сооружения')),
                ('facility_size', models.IntegerField(default=0, verbose_name='Размер сооружения')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вмещаемость')),
                ('photo', models.TextField(default='', verbose_name='Фото')),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WorldCupStatistic.Event', verbose_name='Событие')),
            ],
        ),
    ]
