# Generated by Django 2.1.7 on 2019-03-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorldCupStatistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WorldCupStatistic.Event', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='country',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WorldCupStatistic.Venue', verbose_name='Сооружение'),
        ),
    ]
